name: Basic Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# variables de 
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaults
env:
  NODE_VERSION: '16'

jobs:
  build:
    # runners
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-latest
    # ambientes variables y secretos
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-environments-for-deployment#about-environments
    environment: qa

    steps:
      - id: step1
        name: Print Hello World
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

      - id: step2
        name: Usar variables del output de otro step 
        run: echo ${{ steps.step1.outputs.test }} 

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go version

      - name: test
        run: go run main.go

        