name: Usando Vars y Secrets

on:
  pull_request:
    branches:
      - main
env:
  GO_VERSION: '^1.13.1'

jobs:
  build:
    environment: qa
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version

      - name: Call API
        run: | 
          curl \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            ${{ vars.API_URL }}
        