# nombre que aparece en la UI
name: Custom Actions

# cuando se va a correr este workflow
# The order that you define patterns matters.
# - A matching negative pattern (prefixed with !) after a positive match will exclude the path.
# - A matching positive pattern after a negative match will include the path again.
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
on:
  # se puede agendar usando la nomenclature de cron
  # https://crontab.cronhub.io/
  schedule:
    - cron: "0 11 * * 1" # Monday at 6 AM EST (1100 UTC)

  # cuando hagas push desde tu local o los crees en github
  push: 
    branches:
      - main
      - 'releases/**'
    tags:
      - v2
      - v1.*
    paths:
      - '**.js'
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - 'mona/octocat'
      - 'releases/**-alpha'
    # Sequence of patterns matched against refs/tags
    tags-ignore:
      - v2
      - v1.*
    paths-ignore: 
      - 'docs/**'
  # cuando se cree un pull request que haga merge hacia estos branches
  pull_request:
    types:
      - closed
    branches:
      - main
      - 'releases/**'
      - '!releases/**-alpha'
    branches-ignore:
      - 'mona/octocat'
      - 'releases/**-alpha'
  # interactuando con issue
  issues:
    types:
      - opened
      - labeled
  # especificar los branches donde un job especifico deberia de correr
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'releases/**'
  # workflow_dispatch para workflow reutilizables
  # acepta inputs
  workflow_dispatch:
    # convencion de nombres solo camelcase o underscore
    # description, type, requied, default, option (choice)
    inputs:
      user_name: 
        description: "Username"
        type: string
      logLevel:
        description: "Log level"
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


# env:
#   NODE_VERSION: '16'
#   DAY_OF_WEEK: Monday

jobs:
  # call-workflow-passing-data:
  #   uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
  #   with:
  #     config-path: .github/labeler.yml
  #   secrets:
  #     personal_access_token: ${{ secrets.token }}

  run_if_label_matches:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest

    steps:
      - run: echo 'The label was bug'

  build:
    runs-on: ubuntu-latest
    needs: run_if_label_matches # depends on to run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: custom_action1
        name: Use custom action
        uses: ./.github/actions/custom_action
        # uses: octo-org/example-repo/.github/actions/reusable-action.yml@main
        with: 
          user-name: ${{ github.event.inputs.user_name }}

      - name: 
        run: echo ${{ steps.custom_action1.outputs.random-number }}

      - name: condicional
        if: ${{ inputs.print_tags }} 
        run: echo "si corrio"
        

      