name: DB Clean Up

on:
  workflow_dispatch:

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DB clean up script
        run: |
          bash ./cleanup.sh
        env: 
            LEVEL: "BASIC"