name: Custom Actions

on:
  workflow_dispatch:
    inputs:
      user-name: 
        description: "Username"
        type: string

# env:
#   NODE_VERSION: '16'
#   DAY_OF_WEEK: Monday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: custom_action1
        name: Use custom action
        uses: ./.github/actions/custom_action
        with: 
          user_name: ${{ github.event.inputs.user-name }}

      - name: 
        run: echo ${{ steps.custom_action1.outputs.random-number }}

      