name: Obtener metadatos de PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-pr-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Leer labels del evento de github actions
        run: |
            echo "Event Object"
            ${{ toJson(github.event.pull_request) }}

      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Leer labels y reviewers con GitHub CLI
        run: |
          echo "Labels del PR:"
          gh pr view ${{ env.PR_NUMBER }} 
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # env:
        #   LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
