name: Metadatos del Evento

on:
  pull_request:

jobs:
  read-pr-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Leer PR del evento
        run: |
            echo "Event Object"
            echo "${{ toJson(github.event.pull_request) }}"
            echo "${{ github.event.pull_request.labels }}"
      