name: Metadatos del Evento

on:
  pull_request:

jobs:
  read-pr-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Leer labels del evento de github actions
        run: |
            echo "Event Object"
            echo "${{ toJson(github.event.pull_request) }}"