name: Obtener metadatos de PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  read-pr-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Leer labels y reviewers con GitHub CLI
        id: get-labels
        run: |
          echo "Labels del PR:"
          LABELS=$(gh pr view ${{ env.PR_NUMBER }} --json labels --jq '.labels[].name' | paste -sd "," -)
          echo "labels=$LABELS" >> "$GITHUB_OUTPUT"
        #   echo "Autor del PR:"
        #   gh pr view ${{ env.PR_NUMBER }} --json author --jq '.author.name'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Imprime labels
        run: | 
            echo ${{ steps.get-labels.outputs.labels }}
