name: Cuando creas un Tag

on:
  push: 
    tags:
      - v2
      - v1.*
    tags-ignore:
      - v1.*-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build .......

      - name: docker login 
        run: docker login

      - name: docker push ghcr GitHub Container Registry
        run: docker push ghcr.io/NAMESPACE/IMAGE_NAME:TAG

      - name: deploy to cloud run
        run: gcloud run deploy ......

      