name: Summary Workflow

on:
  workflow_dispatch: 

jobs:
  read-pr-metadata:
    runs-on: ubuntu-latest
    steps:

      - name: Agregar resultados de pruebas
        run: |
          echo "## Resultados"            >> "$GITHUB_STEP_SUMMARY"
          echo ""                         >> "$GITHUB_STEP_SUMMARY"
          echo "- Unit: 120/120 ✅"       >> "$GITHUB_STEP_SUMMARY"
          echo "<hr>"                     >> "$GITHUB_STEP_SUMMARY"
          echo "- Integration: 50/50 ✅"  >> "$GITHUB_STEP_SUMMARY"
          echo "<hr>"                     >> "$GITHUB_STEP_SUMMARY"
          echo "- E2E: 30/30 ✅"          >> "$GITHUB_STEP_SUMMARY"
          
  read-pr-metadata2:
    runs-on: ubuntu-latest
    steps:
      - name: Agregar resultados de pruebas
        run: |
          echo "## Resultados 2"            >> "$GITHUB_STEP_SUMMARY"
          echo ""                         >> "$GITHUB_STEP_SUMMARY"
          echo "- Unit: 120/120 ✅"       >> "$GITHUB_STEP_SUMMARY"

      - name: Agregar resultados de pruebas
        run: |
          echo "## Resultados 3"            >> "$GITHUB_STEP_SUMMARY"
          echo ""                         >> "$GITHUB_STEP_SUMMARY"
          echo "- Unit: 120/120 ✅"       >> "$GITHUB_STEP_SUMMARY"