on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo "principal1"
    outputs: 
      otest1: "Hello1"

  test2:
    runs-on: ubuntu-latest
    needs: [ test1 ]
    if: ${{ !cancelled() && needs.test1.result == 'skipped' }}
    env: 
      TEST1: ${{ toJson(needs.test1.outputs) }}
    steps:
      - run: |
          echo "principal2"
          echo ${TEST1} # will display empty {}
          exit 1
    outputs: 
      otest2: "Hello2"

  test_name: 
    runs-on: ubuntu-latest
    needs: [test2]
    if: ${{ always() }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: test name
        uses: .github/workflows/test-workflow2.yml
        with: 
          name_required: ${{ needs.test2.outputs.otest2 }}

  test3:
    runs-on: ubuntu-latest
    needs: [ test2 ]
    if: ${{ !cancelled() && needs.test2.result == 'success' }}
    steps:
      - run: |
          echo "principal3"
    outputs: 
      otest3: "Hello3"

  test4:
    runs-on: ubuntu-latest
    needs: [ test1, test2, test3 ]
    if: ${{ always() }}
    env: 
      TEST1: ${{ toJson(needs.test1.outputs) }}
      TEST2: ${{ toJson(needs.test2.outputs) }}
      TEST3: ${{ toJson(needs.test3.outputs) }}
    steps:
      - run: |
          echo "principal4"
          echo ${TEST1} # will display empty {}
          echo ${TEST2} # will display {otest3: "Hello3"}
          echo ${TEST3} # will display empty {}
    outputs: 
      otest4: "Hello4"