on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo "principal1"
    outputs: 
      otest1: "Hello1"
  test2:
    runs-on: ubuntu-latest
    needs: [ test1 ]
    if: ${{ needs.test1.result != 'failure' }}
    steps:
      - run: |
          echo "principal2"
    outputs: 
      otest2: "Hello2"
  test3:
    runs-on: ubuntu-latest
    needs: [ test2 ]
    steps:
      - run: |
          echo "principal3"
    outputs: 
      otest3: "Hello3"
     