on:
  workflow_dispatch:
    inputs:
        name_required:
            required: true
            default: "carlos"
            type: string
        name_not_required: 
            required: true
            default: "carlos"
            type: string
        
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Required: ${{ inputs.name_required }}"
          echo "Not Required: ${{ inputs.name_not_required }}"
