name: tests dependencies

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "principal1"
    outputs: 
      otest1: "Hello1"

  test2:
    runs-on: ubuntu-latest
    if: false
    needs: [ test1 ]
    env: 
      TEST1: ${{ toJson(needs.test1.outputs) }}
    steps:
      - run: |
          echo "principal2"
          echo ${TEST1} # will display empty {}
          exit 1
    outputs: 
      otest2: "Hello2"

  test_name: 
    runs-on: ubuntu-latest
    needs: [test1, test2]
    if: ${{ always() }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: test name
        uses: ./.github/actions/test
        with: 
          name_required: ${{ needs.test1.outputs.otest1 }}
          name_non_required: ${{ needs.test2.outputs.otest2 }}

  test3:
    runs-on: ubuntu-latest
    needs: [ test1, test_name ]
    steps:
      - run: |
          echo "this one should skip"
    outputs: 
      otest3: "Hello3"