on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo "principal1"
    outputs: 
      otest1: "Hello1"
  test2:
    runs-on: ubuntu-latest
    needs: [ test1 ]
    if: ${{ always() && needs.test1.result == 'skipped' }}
    steps:
      - run: |
          echo "principal2"
          exit 1
    outputs: 
      otest2: "Hello2"
  test3:
    runs-on: ubuntu-latest
    needs: [ test2 ]
    if: ${{ !cancelled() && needs.test2.result == 'success' }}
    steps:
      - run: |
          echo "principal3"
    outputs: 
      otest3: "Hello3"
     