on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo "principal1"
    outputs: 
      otest1: "Hello1"
  test2:
    runs-on: ubuntu-latest
    needs: [ test1 ]
    if: ${{ !cancelled() && needs.test1.result == 'skipped' }}
    steps:
      - run: |
          echo "principal2"
          exit 1
    outputs: 
      otest2: "Hello2"
  test3:
    runs-on: ubuntu-latest
    needs: [ test2 ]
    if: ${{ !cancelled() && needs.test2.result == 'success' }}
    steps:
      - run: |
          echo "principal3"
    outputs: 
      otest3: "Hello3"
  test4:
    runs-on: ubuntu-latest
    needs: [ test1, test2, test3 ]
    if: ${{ always() }}
    env: 
      TEST1: ${{ toJson(needs.test1.outputs) }}
      TEST2: ${{ toJson(needs.test2.outputs) }}
      TEST3: ${{ toJson(needs.test3.outputs) }}
    steps:
      - run: |
          echo "principal4"
          echo ${TEST1}
          echo ${TEST2}
          echo ${TEST3}
    outputs: 
      otest4: "Hello4"