name: Basic Workflow Dispatch

on:
    workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hola
        run: echo "Hola desde Actions"

      - name: Usar Variables
        run: | 
          echo "NOMBRE: ${{ vars.NOMBRE }}"
      
      - name: Usar Secretos
        run: |
          echo "PASSWORD: ${{ secrets.PASSWORD }}"
